# Generated by Django 4.1.3 on 2022-11-22 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('backoffice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuperPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('nipt', models.CharField(max_length=10, unique=True)),
                ('activity', models.CharField(max_length=30)),
                ('mobile', models.IntegerField()),
                ('jsonDatas', models.JSONField(blank=True, null=True)),
                ('isUpdated', models.CharField(blank=True, default='No', max_length=20, null=True)),
                ('isConfirmed', models.BooleanField(default=False)),
                ('isActive', models.BooleanField(default=False)),
                ('isDeleted', models.BooleanField(default=False)),
                ('createdDate', models.DateTimeField(auto_now_add=True, null=True)),
                ('updatedDate', models.DateTimeField(auto_now=True, null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice.city')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice.member')),
            ],
            options={
                'db_table': 'superpartners',
            },
        ),
    ]
