# Generated by Django 4.1.3 on 2022-11-22 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('backoffice', '0001_initial'),
        ('accountmanagers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountmanager',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member', to='backoffice.member'),
        ),
    ]
