# Generated by Django 4.1.3 on 2022-11-22 14:13

from django.db import migrations, models
import partners.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('code', models.CharField(max_length=500, unique=True)),
                ('isActive', models.BooleanField(default=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('updatedDate', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'action_types',
            },
        ),
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memberType', models.CharField(max_length=200)),
                ('createdProduct', models.CharField(blank=True, max_length=200, null=True)),
                ('createdAm', models.CharField(blank=True, max_length=200, null=True)),
                ('createdUw', models.CharField(blank=True, max_length=200, null=True)),
                ('createdPartner', models.CharField(blank=True, max_length=200, null=True)),
                ('createdSuperPartner', models.CharField(blank=True, max_length=200, null=True)),
                ('createdLoanconfig', models.CharField(blank=True, max_length=200, null=True)),
                ('affectedAm', models.CharField(blank=True, max_length=200, null=True)),
                ('affectedUw', models.CharField(blank=True, max_length=200, null=True)),
                ('affectedProduct', models.CharField(blank=True, max_length=200, null=True)),
                ('affectedPartner', models.CharField(blank=True, max_length=200, null=True)),
                ('affectedSuper_partner', models.CharField(blank=True, max_length=200, null=True)),
                ('affectedCustomer', models.CharField(blank=True, max_length=200, null=True)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'audit',
            },
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255, unique=True)),
                ('isActive', models.BooleanField(default=True)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('updatedDate', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'banks',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cityCode', models.IntegerField(unique=True)),
                ('country', models.CharField(default='Albania', max_length=255)),
                ('isActive', models.BooleanField(default=True)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('updatedDate', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cities',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200, unique=True)),
                ('tmpPass', models.CharField(max_length=200)),
                ('isActive', models.BooleanField(default=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('updatedDate', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'members',
            },
        ),
        migrations.CreateModel(
            name='MemberLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memberType', models.CharField(max_length=200)),
                ('ipAddress', models.CharField(blank=True, max_length=200, null=True)),
                ('loggedIn', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'member_logins',
            },
        ),
        migrations.CreateModel(
            name='MemberType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=250)),
                ('code', models.CharField(max_length=80, unique=True)),
                ('isActive', models.BooleanField(default=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('updatedDate', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'member_types',
            },
        ),
        migrations.CreateModel(
            name='Prelead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appliedAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('approvedAmount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(blank=True, choices=[('ALL', 'ALL'), ('EURO', 'EURO')], default='ALL', max_length=10, null=True)),
                ('loanTerm', models.IntegerField(blank=True, null=True)),
                ('monthlyLoan', models.DecimalField(decimal_places=2, max_digits=10)),
                ('partnerContract', models.FileField(blank=True, null=True, upload_to='files/partner_contracts/%Y/%m/%d/', validators=[partners.validators.validate_file_extension])),
                ('uwContract', models.FileField(blank=True, null=True, upload_to='files/uw_contracts/%Y/%m/%d/', validators=[partners.validators.validate_file_extension])),
                ('doc_1', models.FileField(blank=True, null=True, upload_to='files/additional_docs/%Y/%m/%d/', validators=[partners.validators.validate_file_extension])),
                ('doc_2', models.FileField(blank=True, null=True, upload_to='files/additional_docs/%Y/%m/%d/', validators=[partners.validators.validate_file_extension])),
                ('sellerName', models.CharField(max_length=60)),
                ('sellerPhone', models.CharField(max_length=16)),
                ('applicationStatus', models.CharField(blank=True, default='Pending', max_length=20, null=True)),
                ('rejectionReason', models.CharField(blank=True, max_length=500, null=True)),
                ('isActive', models.BooleanField(default=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('createdDate', models.DateTimeField(auto_now_add=True, null=True)),
                ('updatedDate', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'preleads',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('description', models.CharField(max_length=500)),
                ('minValue', models.FloatField()),
                ('maxValue', models.FloatField()),
                ('term', models.IntegerField()),
                ('isActive', models.BooleanField(default=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('updatedDate', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
