# Generated by Django 4.1.3 on 2022-11-22 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('backoffice', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prelead',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partners.customer'),
        ),
        migrations.AddField(
            model_name='prelead',
            name='partnerProduct',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partners.partnerproduct'),
        ),
        migrations.AddField(
            model_name='memberlogin',
            name='actionType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice.actiontype'),
        ),
        migrations.AddField(
            model_name='memberlogin',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice.member'),
        ),
        migrations.AddField(
            model_name='member',
            name='memberType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberType', to='backoffice.membertype'),
        ),
        migrations.AddField(
            model_name='member',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='audit',
            name='actionType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice.actiontype'),
        ),
        migrations.AddField(
            model_name='audit',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice.member'),
        ),
    ]
